#Replace token with new token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYxMTM1NDI3LCJ1c2VySWQiOiIxIn0.lPXshibiwBjuA8JnuP7IBbjbfbIArM2UFXmYvC2ihiY
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYxMTM1NDExLCJ1c2VySWQiOiIyIn0.W9qOAyRSFRKCAl1BtMNx9mkDScgsxuUqJKjUmEtFwh0
###
GET http://127.0.0.1:8080/users
Content-Type: application/json
Authorization: Bearer {{token}}
###

###
GET http://127.0.0.1:8080/users/4
Content-Type: application/json
Authorization: Bearer {{token}}
###

###
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "username": "Bart",
  "email": "test1@test.nl",
  "password": "Test1"
}
###

###
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "username": "Fauve",
  "email": "test2@test.nl",
  "password": "Test2"
}
###

###
POST http://127.0.0.1:8080/signup
Content-Type: application/json

{
  "username": "Bart",
  "password": "Test1",
  "email": "test1@test.nl"

}
###

###
GET http://127.0.0.1:8080/authenticate
Content-Type: application/json
Authorization: Bearer {{token2}}

###

###
GET http://127.0.0.1:8080/secret
Content-Type: application/json
Authorization: Bearer {{token2}}
###