#Replace token with new token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYxMzEyMDk2LCJ1c2VySWQiOiIyIn0.vIF4fgMjnvZnr099zsn0Aj0GM2idiwS6GD8oUGOoxsw
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwiZXhwIjoxNzYxMTM1NDExLCJ1c2VySWQiOiIyIn0.W9qOAyRSFRKCAl1BtMNx9mkDScgsxuUqJKjUmEtFwh0
###
GET http://127.0.0.1:8080/users
Content-Type: application/json
Authorization: Bearer {{token}}
###

###
GET http://127.0.0.1:8080/users/4
Content-Type: application/json
Authorization: Bearer {{token}}
###

###
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "username": "Bart",
  "email": "test1@test.nl",
  "password": "Test1"
}
###

###
POST http://127.0.0.1:8080/signin
Content-Type: application/json

{
  "username": "Fauve",
  "email": "test2@test.nl",
  "password": "Test2"
}
###

###
POST http://127.0.0.1:8080/signup
Content-Type: application/json

{
  "username": "Bart",
  "password": "Test1",
  "email": "test1@test.nl"

}
###

###
GET http://127.0.0.1:8080/authenticate
Content-Type: application/json
Authorization: Bearer {{token}}

###

###
GET http://127.0.0.1:8080/secret
Content-Type: application/json
Authorization: Bearer {{token}}
###

### get favorites list from user
GET http://127.0.0.1:8080/favourites/1
Content-Type: application/json
Authorization: Bearer {{token}}

### post favorite item to user
POST http://127.0.0.1:8080/favourites/1
Content-Type: application/json
Authorization: Bearer {{token}}